### ISSUE TITLE
OSError: no file with expected extension

### ISSUE THREAD

**Issue by seekingdeep** [hikopensource/DAVAR-Lab-OCR#1]
After installing the requirements, and trying to test the model, i am getting error:

```
(tptron) home@home-lnx:~/programs/DAVAR-Lab-OCR/demo/text_perceptron_det$ python test.py 
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
  File "/home/home/programs/DAVAR-Lab-OCR/mmdetection/mmdet/apis/inference.py", line 34, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/home/home/programs/DAVAR-Lab-OCR/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/home/programs/DAVAR-Lab-OCR/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/home/programs/DAVAR-Lab-OCR/mmdetection/mmdet/utils/registry.py", line 79, in build_from_cfg
    return obj_cls(**args)
  File "/home/home/programs/DAVAR-Lab-OCR/mmdetection/third_party/text_perceptron/mmdet/models/detectors/text_perceptron_det.py", line 59, in __init__
    self.shape_transform_module = build_roi_extractor(shape_transform_module)
  File "/home/home/programs/DAVAR-Lab-OCR/mmdetection/mmdet/models/builder.py", line 27, in build_roi_extractor
    return build(cfg, ROI_EXTRACTORS)
  File "/home/home/programs/DAVAR-Lab-OCR/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/home/programs/DAVAR-Lab-OCR/mmdetection/mmdet/utils/registry.py", line 79, in build_from_cfg
    return obj_cls(**args)
  File "/home/home/programs/DAVAR-Lab-OCR/mmdetection/third_party/text_perceptron/mmdet/models/shape_transform_module/points_generation.py", line 71, in __init__
    lib = ctl.load_library(lib_name, lib_dir)
  File "/home/home/anaconda3/envs/tptron/lib/python3.7/site-packages/numpy/ctypeslib.py", line 153, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
```

**Comment by seekingdeep** [comment]
Are the requirements causing this error?
if so, then upload the requirements using:
```
conda env export > environment.yml
```
