### ISSUE TITLE
OSError: no file with expected extension  ( I don't know how to solve it.)

### ISSUE THREAD

**Issue by lmmlzn** [hikopensource/DAVAR-Lab-OCR#129]
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
fatal: Not a git repository (or any parent up to mount point /wolf)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /wolf)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2022-10-26 18:26:19,305 - davarocr - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.0 (default, Nov  6 2019, 21:49:08) [GCC 7.3.0]
CUDA available: True
GPU 0,1: NVIDIA TITAN X (Pascal)
CUDA_HOME: /usr/local/cuda-9.0
NVCC: Cuda compilation tools, release 9.0, V9.0.176
GCC: gcc (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0
OpenCV: 4.6.0
MMCV: 1.3.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
DAVAROCR: 0.6.0+
------------------------------------------------------------

2022-10-26 18:26:19,909 - davarocr - INFO - Distributed training: True
2022-10-26 18:26:20,500 - davarocr - INFO - Config:
model = dict(
    type='LGPMA',
    pretrained='/wolf/ly/liu/DAVAR-Lab-OCR-main/resnet50-19c8e357.pth',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[4, 8, 16],
            ratios=[0.05, 0.1, 0.2, 0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(
            type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=1.0)),
    roi_head=dict(
        type='LGPMARoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=2,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        mask_head=dict(
            type='LPMAMaskHead',
            num_convs=4,
            in_channels=256,
            conv_out_channels=256,
            num_classes=2,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0),
            loss_lpma=dict(type='L1Loss', loss_weight=1.0))),
    global_seg_head=dict(
        type='GPMAMaskHead',
        in_channels=256,
        conv_out_channels=256,
        num_classes=1,
        loss_mask=dict(type='DiceLoss', loss_weight=1),
        loss_reg=dict(
            type='SmoothL1Loss', beta=0.1, loss_weight=0.01, reduction='sum')),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms_post=2000,
            nms=dict(type='nms', iou_threshold=0.5),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            mask_size=28,
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=2000,
            nms_post=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.5),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.1),
            max_per_img=1000,
            mask_thr_binary=0.5),
        postprocess=dict(type='PostLGPMA', refine_bboxes=False)))
train_cfg = None
test_cfg = None
dataset_type = 'TableRcgDataset'
data_root = ''
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='DavarLoadImageFromFile'),
    dict(
        type='DavarLoadTableAnnotations',
        with_bbox=True,
        with_enlarge_bbox=True,
        with_label=True,
        with_poly_mask=True,
        with_empty_bbox=True),
    dict(
        type='DavarResize',
        img_scale=[(360, 480), (960, 1080)],
        keep_ratio=True,
        multiscale_mode='range'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='GPMADataGeneration'),
    dict(type='DavarDefaultFormatBundle'),
    dict(
        type='DavarCollect',
        keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks', 'gt_semantic_seg'])
]
val_pipeline = [
    dict(type='DavarLoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        scale_factor=1.5,
        flip=False,
        transforms=[
            dict(type='DavarResize', keep_ratio=True),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DavarDefaultFormatBundle'),
            dict(type='DavarCollect', keys=['img'])
        ])
]
test_pipeline = [
    dict(type='DavarLoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        scale_factor=1.5,
        flip=False,
        transforms=[
            dict(type='DavarResize', keep_ratio=True),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DavarDefaultFormatBundle'),
            dict(type='DavarCollect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='TableRcgDataset',
        ann_file=
        '/wolf/ly/liu/DAVAR-Lab-OCR-main/demo/table_recognition/datalist/datalist_train_detection_pubtabnet.json',
        img_prefix='/wolf/ly/liu_pubtabnet/Images/train/',
        pipeline=[
            dict(type='DavarLoadImageFromFile'),
            dict(
                type='DavarLoadTableAnnotations',
                with_bbox=True,
                with_enlarge_bbox=True,
                with_label=True,
                with_poly_mask=True,
                with_empty_bbox=True),
            dict(
                type='DavarResize',
                img_scale=[(360, 480), (960, 1080)],
                keep_ratio=True,
                multiscale_mode='range'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='GPMADataGeneration'),
            dict(type='DavarDefaultFormatBundle'),
            dict(
                type='DavarCollect',
                keys=[
                    'img', 'gt_bboxes', 'gt_labels', 'gt_masks',
                    'gt_semantic_seg'
                ])
        ]),
    val=dict(
        type='TableRcgDataset',
        ann_file='path/to/validation.json',
        img_prefix='path/to/PubTabNet',
        pipeline=[
            dict(type='DavarLoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                scale_factor=1.5,
                flip=False,
                transforms=[
                    dict(type='DavarResize', keep_ratio=True),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DavarDefaultFormatBundle'),
                    dict(type='DavarCollect', keys=['img'])
                ])
        ]),
    test=dict(
        type='TableRcgDataset',
        ann_file='path/to/PubTabNet_2.0.0_val.jsonl',
        img_prefix='path/to/PubTabNet/Images/val/',
        pipeline=[
            dict(type='DavarLoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                scale_factor=1.5,
                flip=False,
                transforms=[
                    dict(type='DavarResize', keep_ratio=True),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DavarDefaultFormatBundle'),
                    dict(type='DavarCollect', keys=['img'])
                ])
        ],
        samples_per_gpu=1))
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=1000,
    warmup_ratio=0.3333333333333333,
    step=[6, 10])
runner = dict(type='EpochBasedRunner', max_epochs=12)
checkpoint_config = dict(
    interval=1, filename_tmpl='checkpoint/maskrcnn-lgpma-pub-e{}.pth')
log_config = dict(interval=10, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = '/home/jinac/liu/DAVAR-Lab-OCR-main/work_dir'
load_from = None
resume_from = None
workflow = [('train', 1)]
evaluation_metric = 'TEDS'
evaluation = dict(
    eval_func_params=dict(ENLARGE_ANN_BBOXES=True, IOU_CONSTRAINT=0.5),
    metric='TEDS',
    by_epoch=True,
    interval=1,
    eval_mode='general',
    save_best='TEDS',
    rule='greater')
gpu_ids = range(0, 2)

2022-10-26 18:26:21,052 - mmdet - INFO - load model from: /wolf/ly/liu/DAVAR-Lab-OCR-main/resnet50-19c8e357.pth
2022-10-26 18:26:21,052 - mmdet - INFO - Use load_from_local loader
2022-10-26 18:26:21,267 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

Traceback (most recent call last):
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_table/datasets/pipelines/gpma_data.py", line 50, in __init__
    lib = ctl.load_library(lib_name, lib_dir)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/numpy/ctypeslib.py", line 163, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_table/datasets/table_rcg_dataset.py", line 48, in __init__
    super().__init__(ann_file, pipeline, data_root, img_prefix, seg_prefix, proposal_file, test_mode,
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_common/datasets/davar_custom.py", line 135, in __init__
    self.pipeline = Compose(pipeline)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: GPMADataGeneration: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/wolf/ly/liu/DAVAR-Lab-OCR-main/tools/train.py", line 252, in <module>
    main()
  File "/wolf/ly/liu/DAVAR-Lab-OCR-main/tools/train.py", line 227, in main
    datasets = [davar_build_dataset(cfg.data.train)]
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_common/datasets/builder.py", line 229, in davar_build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: TableRcgDataset: GPMADataGeneration: no file with expected extension
Traceback (most recent call last):
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_table/datasets/pipelines/gpma_data.py", line 50, in __init__
    lib = ctl.load_library(lib_name, lib_dir)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/numpy/ctypeslib.py", line 163, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_table/datasets/table_rcg_dataset.py", line 48, in __init__
    super().__init__(ann_file, pipeline, data_root, img_prefix, seg_prefix, proposal_file, test_mode,
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_common/datasets/davar_custom.py", line 135, in __init__
    self.pipeline = Compose(pipeline)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: GPMADataGeneration: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/wolf/ly/liu/DAVAR-Lab-OCR-main/tools/train.py", line 252, in <module>
    main()
  File "/wolf/ly/liu/DAVAR-Lab-OCR-main/tools/train.py", line 227, in main
    datasets = [davar_build_dataset(cfg.data.train)]
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_common/datasets/builder.py", line 229, in davar_build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: TableRcgDataset: GPMADataGeneration: no file with expected extension
Traceback (most recent call last):
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/jinac/anaconda3/envs/lgpma/bin/python', '-u', '/wolf/ly/liu/DAVAR-Lab-OCR-main/tools/train.py', '--local_rank=1', './configs/lgpma_pub.py', '--no-validate', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by lmmlzn** [comment]
求救

**Comment by qiaoliang6** [comment]
#31

**Comment by lmmlzn** [comment]
@qiaoliang6  g++ -shared -o ./davarocr/davar_table/datasets/pipelines/lib/gpma_data.so -fPIC ./davarocr/davar_table/datasets/pipelines/lib/gpma_data.cpp `pkg-config --cflags --libs opencv`

但是我用了这个以后 有gpma_data.so文件了，还是报了错

错误：
Traceback (most recent call last):
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_table/datasets/pipelines/gpma_data.py", line 50, in __init__
    lib = ctl.load_library(lib_name, lib_dir)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/numpy/ctypeslib.py", line 163, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_table/datasets/table_rcg_dataset.py", line 48, in __init__
    super().__init__(ann_file, pipeline, data_root, img_prefix, seg_prefix, proposal_file, test_mode,
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/davarocr-0.6.0-py3.8.egg/davarocr/davar_common/datasets/davar_custom.py", line 135, in __init__
    self.pipeline = Compose(pipeline)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: GPMADataGeneration: no file with expected extension

**Comment by qiaoliang6** [comment]
> 

可以试一下在配置config中手动指定一下中用到这个.so文件的绝对路径，GPMADataGeneration模块中修改的lib_name和lib_dir
