### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by lmmlzn** [hikopensource/DAVAR-Lab-OCR#130]
Traceback (most recent call last):
  File "/wolf/ly/liu/DAVAR-Lab-OCR-main/tools/train.py", line 14, in <module>
    import cv2
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/jinac/anaconda3/envs/lgpma/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen: cannot load any more object with static TLS

**Comment by qiaoliang6** [comment]
This problem seems caused by the version conflict between 'cv2' and 'sklearn' packages, and has no realtion with davarocr. You may search and try some solution from Google.
