### ISSUE TITLE
运行bash dist_train.sh报错。

### ISSUE THREAD

**Issue by yangguangjie** [hikopensource/DAVAR-Lab-OCR#134]
您好，我运行bash dist_train.sh报如下错误，请问是什么原因，环境问题吗（环境直接运行的setup.sh安装的），非常感谢
/home/luhu/anaconda3/envs/davar/bin/python: can't open file '/path/to/Davar-Lab-OCR//tools/train.py': [Errno 2] No such file or directory
/home/luhu/anaconda3/envs/davar/bin/python: can't open file '/path/to/Davar-Lab-OCR//tools/train.py': [Errno 2] No such file or directory
/home/luhu/anaconda3/envs/davar/bin/python: can't open file '/path/to/Davar-Lab-OCR//tools/train.py': [Errno 2] No such file or directory
/home/luhu/anaconda3/envs/davar/bin/python: can't open file '/path/to/Davar-Lab-OCR//tools/train.py': [Errno 2] No such file or directory
/home/luhu/anaconda3/envs/davar/bin/python: can't open file '/path/to/Davar-Lab-OCR//tools/train.py': [Errno 2] No such file or directory
/home/luhu/anaconda3/envs/davar/bin/python: can't open file '/path/to/Davar-Lab-OCR//tools/train.py': [Errno 2] No such file or directory
Killing subprocess 152393
Killing subprocess 152394
Killing subprocess 152395
Killing subprocess 152396
Killing subprocess 152397
Killing subprocess 152398
Killing subprocess 152399
Killing subprocess 152400
Traceback (most recent call last):
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/luhu/anaconda3/envs/davar/bin/python', '-u', '/path/to/Davar-Lab-OCR//tools/train.py', '--local_rank=7', './configs/lgpma_pub.py', '--no-validate', '--launcher', 'pytorch']' returned non-zero exit status 2.

**Comment by icedream2** [comment]
根据提示，你需要你路径'/path/to/Davar-Lab-OCR//tools/train.py' 改成你自己环境中的路径
