### ISSUE TITLE
运行train报错OSError: TableRcgDataset: GPMADataGeneration: no file with expected extension

### ISSUE THREAD

**Issue by yangguangjie** [hikopensource/DAVAR-Lab-OCR#141]
Traceback (most recent call last):
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/luhu/code/DAVAR-Lab-OCR/davarocr/davar_table/datasets/pipelines/gpma_data.py", line 50, in __init__
    lib = ctl.load_library(lib_name, lib_dir)
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/site-packages/numpy/ctypeslib.py", line 154, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/luhu/code/DAVAR-Lab-OCR/davarocr/davar_table/datasets/table_rcg_dataset.py", line 49, in __init__
    filter_empty_gt, classes_config)
  File "/home/luhu/code/DAVAR-Lab-OCR/davarocr/davar_common/datasets/davar_custom.py", line 135, in __init__
    self.pipeline = Compose(pipeline)
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: GPMADataGeneration: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luhu/code/DAVAR-Lab-OCR/tools/train.py", line 255, in <module>
    main()
  File "/home/luhu/code/DAVAR-Lab-OCR/tools/train.py", line 230, in main
    datasets = [davar_build_dataset(cfg.data.train)]
  File "/home/luhu/code/DAVAR-Lab-OCR/davarocr/davar_common/datasets/builder.py", line 229, in davar_build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/luhu/anaconda3/envs/davar/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: TableRcgDataset: GPMADataGeneration: no file with expected extension

**Comment by qiaoliang6** [comment]
Please refer to #31 and #129
