### ISSUE TITLE
run test_pub.py error

### ISSUE THREAD

**Issue by tianyongliu** [hikopensource/DAVAR-Lab-OCR#143]
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.2'
Traceback (most recent call last):
  File "demo/table_recognition/lgpma/tools/test_pub.py", line 17, in <module>
    from davarocr.davar_table.utils import TEDS, format_html
  File "/root/workspace/DAVAR-Lab-OCR-main/davarocr/__init__.py", line 11, in <module>
    from .davar_common import *
  File "/root/workspace/DAVAR-Lab-OCR-main/davarocr/davar_common/__init__.py", line 11, in <module>
    from .models import *
  File "/root/workspace/DAVAR-Lab-OCR-main/davarocr/davar_common/models/__init__.py", line 11, in <module>
    from mmdet.models.builder import (BACKBONES, DETECTORS, HEADS, LOSSES, NECKS,
  File "/root/miniconda/envs/davar/lib/python3.8/site-packages/mmdet/models/__init__.py", line 6, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/root/miniconda/envs/davar/lib/python3.8/site-packages/mmdet/models/dense_heads/__init__.py", line 1, in <module>
    from .anchor_free_head import AnchorFreeHead
  File "/root/miniconda/envs/davar/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_free_head.py", line 8, in <module>
    from mmdet.core import multi_apply
  File "/root/miniconda/envs/davar/lib/python3.8/site-packages/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/root/miniconda/envs/davar/lib/python3.8/site-packages/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/root/miniconda/envs/davar/lib/python3.8/site-packages/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/root/miniconda/envs/davar/lib/python3.8/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 2, in <module>
    from mmcv.ops import nms_match
  File "/root/miniconda/envs/davar/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/root/miniconda/envs/davar/lib/python3.8/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/root/miniconda/envs/davar/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/root/miniconda/envs/davar/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /root/miniconda/envs/davar/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE

my dependence:
(davar) [root@iZwz9fyqge9g3c56q48ejiZ DAVAR-Lab-OCR-main]# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

(davar) [root@iZwz9fyqge9g3c56q48ejiZ DAVAR-Lab-OCR-main]# pip list|grep torch
torch                  1.10.0
torchaudio             0.10.0
torchvision            0.11.0
warpctc-pytorch        0.1

@qiaoliang6  help!!!

**Comment by tianyongliu** [comment]
安装  pytorch==1.8 已经解决环境问题，但是用单卡训练的时候遇到了另外的问题，我下载 resnet50-19c8e357.pth， 训练的时候报错。

2023-02-28 11:03:14,078 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

WARNING:mmdet:The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

**Comment by tianyongliu** [comment]
Thank you!Solved by install pytorch==1.8
