### ISSUE TITLE
运行test_pub.py 报错

### ISSUE THREAD

**Issue by Floyd809** [hikopensource/DAVAR-Lab-OCR#19]
您好，我们在学习您的表格识别代码。但是无法运行推理脚本，报错如下：
Traceback (most recent call last):
  File "/home/ihavc01/Downloads/LG/DAVAR-Lab-OCR-main/demo/table_recognition/lgpma/tools/test_pub.py", line 19, in <module>
    from davarocr.davar_common.apis import inference_model, init_model
  File "/home/ihavc01/Downloads/LG/DAVAR-Lab-OCR-main/davarocr/davarocr/__init__.py", line 11, in <module>
    from .davar_common import *
  File "/home/ihavc01/Downloads/LG/DAVAR-Lab-OCR-main/davarocr/davarocr/davar_common/__init__.py", line 11, in <module>
    from .models import *
  File "/home/ihavc01/Downloads/LG/DAVAR-Lab-OCR-main/davarocr/davarocr/davar_common/models/__init__.py", line 11, in <module>
    from mmdet.models.builder import (BACKBONES, DETECTORS, HEADS, LOSSES, NECKS,
  File "/home/ihavc01/anaconda3/envs/python36/lib/python3.6/site-packages/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/ihavc01/anaconda3/envs/python36/lib/python3.6/site-packages/mmdet/models/backbones/__init__.py", line 1, in <module>
    from .darknet import Darknet
  File "/home/ihavc01/anaconda3/envs/python36/lib/python3.6/site-packages/mmdet/models/backbones/darknet.py", line 6, in <module>
    from mmcv.cnn import ConvModule, constant_init, kaiming_init
  File "/home/ihavc01/anaconda3/envs/python36/lib/python3.6/site-packages/mmcv/cnn/__init__.py", line 14, in <module>
    from .builder import MODELS, build_model_from_cfg
  File "/home/ihavc01/anaconda3/envs/python36/lib/python3.6/site-packages/mmcv/cnn/builder.py", line 1, in <module>
    from ..runner import Sequential
  File "/home/ihavc01/anaconda3/envs/python36/lib/python3.6/site-packages/mmcv/runner/__init__.py", line 3, in <module>
    from .base_runner import BaseRunner
  File "/home/ihavc01/anaconda3/envs/python36/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 13, in <module>
    from .checkpoint import load_checkpoint
  File "/home/ihavc01/anaconda3/envs/python36/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 14, in <module>
    import torchvision
  File "/home/ihavc01/.local/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/ihavc01/.local/lib/python3.6/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/ihavc01/.local/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/ihavc01/.local/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/ihavc01/.local/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/ihavc01/.local/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

请问能否帮助解答该问题如何解决？谢谢！！

**Comment by qiaoliang6** [comment]
看上去像是cuda版本的问题，可以先排查一下cuda版本是否匹配。或者参考一下docs/FAQ中关于warpctc引用报错的解决方法。
另外，如果暂时不需要使用到该模块，可以在__init__.py暂时把相关的引用注释掉，不会影响到其他模块的运行。
