### ISSUE TITLE
Please add demo for using DAVAR-Lab-OCR in colab

### ISSUE THREAD

**Issue by PoornaSaiNagendra** [hikopensource/DAVAR-Lab-OCR#26]
Could you add a demo ipynb notebooks for table_recognition, text_detection, text_ie, text_recognition, text_spotting, videotext to work in colab.

**Comment by qiaoliang6** [comment]
Thank you for your suggestion. We will add more details to optimize the demos, including how to used separate modules and how can different algorithms work in a pipeline, etc.

**Comment by qiaoliang6** [comment]
Thank you for your suggestion. We will consider adding more details to optimize the demos, such as how to used separate modules and how can different algorithms work in a pipeline

**Comment by qiaoliang6** [comment]
Thank you for your suggestion. We will consider adding more details to optimize the demos, such as how to used separate modules and how can different algorithms work in a pipeline

**Comment by Melek-Sahlia** [comment]
Hello, thank you for the contribution. I am facing some troubles with how to run the project :/. Can you provide us with a demo on how to run it, please?

**Comment by leminhyen2** [comment]
I hope to see a demo too. There is no instruction to run this repo at all beside training and evaluate default dataset

**Comment by light42** [comment]
Seconded this, without concrete demo it's really hard to test. When I tried it using google-colab, turns out the packages dependencies is a mess, and I ended up reinstalled some packages to different versions to avoid conflict.

And when the installation is complete, I still found issue when trying table recognition.
Here's the error message:
`Use load_from_local loader
Traceback (most recent call last):
  File "tools/test_pub_with_ocr.py", line 71, in <module>
    model_lgpma = init_model(config_lgpma, checkpoint_lgpma)
  File "/content/DAVAR-Lab-OCR/davarocr/davar_common/apis/inference.py", line 68, in init_model
    checkpoint = load_checkpoint(model, checkpoint, map_location=map_loc)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/checkpoint.py", line 261, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f2196b0f193 in /usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f2199c979eb in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f2199c98c04 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c1ef6 (0x7f21e1bc4ef6 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x295928 (0x7f21e1798928 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so)
frame #5: python3() [0x5d746e]
<omitting python frames>
frame #7: python3() [0x4ff485]
frame #9: python3() [0x4bdd6e]
frame #15: python3() [0x586306]
frame #20: python3() [0x49ced5]
frame #22: python3() [0x49ec69]
frame #23: python3() [0x4fdff5]
frame #24: python3() [0x49caa1]
frame #27: python3() [0x49ec69]
frame #30: python3() [0x49ced5]
frame #33: python3() [0x49ec69]
frame #36: python3() [0x642140]
frame #37: python3() [0x6421be]
frame #38: python3() [0x644688]
frame #42: __libc_start_main + 0xe7 (0x7f21fb258c87 in /lib/x86_64-linux-gnu/libc.so.6)`
