### ISSUE TITLE
TRIE test issue

### ISSUE THREAD

**Issue by kbrajwani** [hikopensource/DAVAR-Lab-OCR#5]
i have download wildreciept dataset and set the path of it. but still i am getting following error. Can you please help me?

```
/content/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/datasets/pipelines/davar_loading.py:228: UserWarning: sensitive type should be in ["lower","upper","same"], but found same other inputs will be treated as "same" automatically
  ' other inputs will be treated as "same" automatically'.format(self.sensitive))
Use load_from_local loader
[                                                  ] 0/472, elapsed: 0s, ETA:/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "./davarocr/tools/test.py", line 261, in <module>
    main()
  File "./davarocr/tools/test.py", line 231, in main
    args.show_score_thr, model_type)
  File "/content/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/apis/test.py", line 51, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/content/DAVAR-Lab-OCR/davarocr/davarocr/davar_spotting/models/spotters/base.py", line 70, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/content/DAVAR-Lab-OCR/davarocr/davarocr/davar_spotting/models/spotters/base.py", line 61, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/content/DAVAR-Lab-OCR/davarocr/davarocr/davar_ie/models/trie/trie_gt.py", line 294, in simple_test
    bieo_labels=None)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DAVAR-Lab-OCR/davarocr/davarocr/davar_ie/models/connects/multimodal_context_module.py", line 214, in forward
    bieo_labels=bieo_labels)
  File "/content/DAVAR-Lab-OCR/davarocr/davarocr/davar_ie/models/connects/multimodal_context_module.py", line 132, in pack_batch
    b_s = pos_feat[_].size(0)
TypeError: list indices must be integers or slices, not tuple
```

**Comment by qiaoliang6** [comment]
We have fixed this issue in the latest commit: 347e2d2578b6d9d523661ae8ed5abf1b9ee102f0

**Comment by kbrajwani** [comment]
Thanks. Can you please tell me how to use --show-dir args in TRIE to see painted images.

**Comment by qiaoliang6** [comment]
Currently, the code is not support for visualization of TRIE. The --show-dir is just a reserved arg from mmdetection.  Visualizations can be simply achieved in the test script and we will also provide some demos soon.

**Comment by kbrajwani** [comment]
Thanks for support.
