### ISSUE TITLE
why train time is too long for LGPMA?

### ISSUE THREAD

**Issue by cv-small-snails** [hikopensource/DAVAR-Lab-OCR#58]
I try to train LGPMA model using your datalist, but I find train time is to long about  20 day? Why?

**Comment by qiaoliang6** [comment]
The dataset of pubtabnet is a large dataset containing about 500,000 images, so the training time is relatively long. It also depends on how many GPUs and the GPU's capacities. In our experiment, training the model on 8 32G-Teslas-V100 for 12 epochs costs less than 1 day.  You may reduce the number of dataset/ training epochs to save time.

**Comment by cv-small-snails** [comment]
OK I understand.  my GPU is 2080,  It is not very good.
another question, have you used fintabnet dataset？
I run official dataset notebooks, But the result looks not correct, as shown below
![Figure_1](https://user-images.githubusercontent.com/18139836/154601832-38d13d2f-9217-4c45-966b-7a3c65d2c242.png)

Do you know why？

**Comment by qiaoliang6** [comment]
Sorry we have not used this dataset.

**Comment by cv-small-snails** [comment]
> Sorry we have not used this dataset.

OK, Thank you for your reply too

**Comment by cv-small-snails** [comment]
> Which dataset is this?

Fintabnet dataset contains complex tables from the annual reports of S&P 500 companies with detailed table structure annotations to help train and test structure recognition. For more details you can see [fintabnet](https://developer.ibm.com/exchanges/data/all/fintabnet/)

If you need more dataset, you can see this [repo](https://github.com/cv-small-snails/Awesome-Table-Recognition).

**Comment by javierztl** [comment]
Hi @cv-small-snails   @qiaoliang6 , can you please help figure out the correct val dataset while training.  the default is the original annotation file(PubTabNet 2.0.0.jsonl), do I need to convert it to davar format. 
I use the original annotation and the problem below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/usr/local/lib/python3.8/dist-packages/davarocr-0.4.0-py3.8.egg/davarocr/davar_common/datasets/davar_custom.py", line 116, in __init__
    data_infos = self.load_annotations(self.ann_file)
  File "/usr/local/lib/python3.8/dist-packages/davarocr-0.4.0-py3.8.egg/davarocr/davar_common/datasets/davar_custom.py", line 218, in load_annotations
    return self._load_json(ann_file)
  File "/usr/local/lib/python3.8/dist-packages/davarocr-0.4.0-py3.8.egg/davarocr/davar_common/datasets/davar_custom.py", line 151, in _load_json
    ann = json.load(load_f, object_pairs_hook=collections.OrderedDict)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 1641)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 251, in <module>
    main()
  File "tools/train.py", line 240, in main
    train_model(
  File "/usr/local/lib/python3.8/dist-packages/davarocr-0.4.0-py3.8.egg/davarocr/davar_common/apis/train.py", line 143, in train_model
    val_dataset = davar_build_dataset(cfg.data.val, dict(test_mode=True))
  File "/usr/local/lib/python3.8/dist-packages/davarocr-0.4.0-py3.8.egg/davarocr/davar_common/datasets/builder.py", line 230, in davar_build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

**Comment by javierztl** [comment]
solved, it should be davar format.
